"""
agent_item_text automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .agent_item import AgentItem


# Text agent message
class AgentItemText(AgentItem):
    type: Literal["text"] = Field(alias="type")
    content: Optional[str] = Field(default=None, alias="content")


