"""
backend_sdk_generate automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class BackendSdkGenerate(BaseModel):
    format: Optional[str] = Field(default=None, alias="format")
    config: Optional[str] = Field(default=None, alias="config")
    pass


