"""
backend_action automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from .backend_action_config import BackendActionConfig
from .common_metadata import CommonMetadata
@dataclass_json
@dataclass
class BackendAction:
    id: int = field(default=None, metadata=config(field_name="id"))
    status: int = field(default=None, metadata=config(field_name="status"))
    name: str = field(default=None, metadata=config(field_name="name"))
    _class: str = field(default=None, metadata=config(field_name="class"))
    async: bool = field(default=None, metadata=config(field_name="async"))
    config: BackendActionConfig = field(default=None, metadata=config(field_name="config"))
    metadata: CommonMetadata = field(default=None, metadata=config(field_name="metadata"))
