"""
backend_form automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .common_metadata import CommonMetadata


# This object represents a form which helps to dynamically generate a form at a frontend app
class BackendForm(BaseModel):
    id: Optional[int] = Field(default=None, alias="id")
    status: Optional[int] = Field(default=None, alias="status")
    name: Optional[str] = Field(default=None, alias="name")
    operation_id: Optional[int] = Field(default=None, alias="operationId")
    ui_schema: Optional[Any] = Field(default=None, alias="uiSchema")
    metadata: Optional[CommonMetadata] = Field(default=None, alias="metadata")
    pass


