"""
backend_role automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from typing import List
@dataclass_json
@dataclass
class BackendRole:
    id: int = field(default=None, metadata=config(field_name="id"))
    category_id: int = field(default=None, metadata=config(field_name="categoryId"))
    name: str = field(default=None, metadata=config(field_name="name"))
    scopes: List[str] = field(default=None, metadata=config(field_name="scopes"))
