"""
backend_account_change_password automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class BackendAccountChangePassword:
    old_password: str = field(default=None, metadata=config(field_name="oldPassword"))
    new_password: str = field(default=None, metadata=config(field_name="newPassword"))
    verify_password: str = field(default=None, metadata=config(field_name="verifyPassword"))
