"""
backend_dashboard_transaction automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
import datetime
class BackendDashboardTransaction(BaseModel):
    id: Optional[int] = Field(default=None, alias="id")
    status: Optional[str] = Field(default=None, alias="status")
    provider: Optional[str] = Field(default=None, alias="provider")
    transaction_id: Optional[str] = Field(default=None, alias="transactionId")
    amount: Optional[float] = Field(default=None, alias="amount")
    date: Optional[datetime.datetime] = Field(default=None, alias="date")
    pass
