"""
backend_scope_category_scope automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class BackendScopeCategoryScope:
    id: int = field(metadata=config(field_name="id"))
    name: str = field(metadata=config(field_name="name"))
    description: str = field(metadata=config(field_name="description"))
