"""
backend_operation_throws automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from typing import Dict
class BackendOperationThrows(Dict[str, str]):
    pass
