"""
backend_rate_collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .common_collection import CommonCollection
from .backend_rate import BackendRate


# A paginated collection of rate objects
class BackendRateCollection(CommonCollection[BackendRate]):
    pass


