"""
backend_webhook_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class BackendWebhookResponse:
    id: int = field(metadata=config(field_name="id"))
    status: int = field(metadata=config(field_name="status"))
    code: int = field(metadata=config(field_name="code"))
    attempts: int = field(metadata=config(field_name="attempts"))
    error: str = field(metadata=config(field_name="error"))
    execute_date: datetime.datetime = field(metadata=config(field_name="executeDate"))
