"""
backend_category_update automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from backend_category import BackendCategory
@dataclass_json
@dataclass
class BackendCategoryUpdate(BackendCategory):
