"""
backend_schema_preview_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class BackendSchemaPreviewResponse(BaseModel):
    preview: Optional[str] = Field(default=None, alias="preview")
    pass


