"""
backend_agent_message_tool_call automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .backend_agent_message import BackendAgentMessage
from .backend_agent_message_tool_call_function import BackendAgentMessageToolCallFunction


# Tool call agent result
class BackendAgentMessageToolCall(BackendAgentMessage):
    type: Literal["tool_call"] = Field(alias="type")
    functions: Optional[List[BackendAgentMessageToolCallFunction]] = Field(default=None, alias="functions")
    pass


