"""
backend_trigger automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .common_metadata import CommonMetadata


# This object represents a trigger which can invoke an action on a custom event
class BackendTrigger(BaseModel):
    kind: Optional[str] = Field(default=None, alias="kind")
    id: Optional[int] = Field(default=None, alias="id")
    name: Optional[str] = Field(default=None, alias="name")
    event: Optional[str] = Field(default=None, alias="event")
    action: Optional[str] = Field(default=None, alias="action")
    metadata: Optional[CommonMetadata] = Field(default=None, alias="metadata")


