"""
backend_specification_publish automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal


class BackendSpecificationPublish(BaseModel):
    name: Optional[str] = Field(default=None, alias="name")
    filter_name: Optional[str] = Field(default=None, alias="filterName")
    standalone: Optional[bool] = Field(default=None, alias="standalone")
    pass


