"""
backend_agent_message_choice automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .backend_agent_message import BackendAgentMessage
from .backend_agent_message_binary import BackendAgentMessageBinary
from .backend_agent_message_object import BackendAgentMessageObject
from .backend_agent_message_text import BackendAgentMessageText
from .backend_agent_message_tool_call import BackendAgentMessageToolCall


# Choice agent result
class BackendAgentMessageChoice(BackendAgentMessage):
    type: Literal["choice"] = Field(alias="type")
    items: List[Annotated[Union["BackendAgentMessageBinary", "BackendAgentMessageChoice", "BackendAgentMessageObject", "BackendAgentMessageText", "BackendAgentMessageToolCall"], Field(discriminator="type")]] = Field(alias="items")
    pass


