"""
backend_audit_object automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import Any
from typing import Dict


# A key value object containing the changes
class BackendAuditObject(Dict[str, Any]):
    pass
