"""
backend_log automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
from backend_log_error import BackendLogError
@dataclass_json
@dataclass
class BackendLog:
    id: int
    ip: str
    user_agent: str
    method: str
    path: str
    header: str
    body: str
    date: datetime.datetime
    errors: List[BackendLogError]
