"""
backend_specification_get automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal


class BackendSpecificationGet(BaseModel):
    spec: Optional[Any] = Field(default=None, alias="spec")
    pass


