"""
backend_app_update automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from .backend_app import BackendApp
@dataclass_json
@dataclass
class BackendAppUpdate(BackendApp):
