"""
backend_schema_preview_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class BackendSchemaPreviewResponse:
    preview: str = field(default=None, metadata=config(field_name="preview"))
