"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List

from .authorization_tag import AuthorizationTag
from .system_tag import SystemTag
from .consumer_tag import ConsumerTag
from .backend_tag import BackendTag

class Client(sdkgen.ClientAbstract):
    @classmethod
    def __init__(cls, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)

    @classmethod
    def authorization(cls) -> AuthorizationTag:
        return AuthorizationTag(
            cls.http_client,
            cls.parser
        )

    @classmethod
    def system(cls) -> SystemTag:
        return SystemTag(
            cls.http_client,
            cls.parser
        )

    @classmethod
    def consumer(cls) -> ConsumerTag:
        return ConsumerTag(
            cls.http_client,
            cls.parser
        )

    @classmethod
    def backend(cls) -> BackendTag:
        return BackendTag(
            cls.http_client,
            cls.parser
        )



    @staticmethod
    def build(clientId: str, clientSecret: str, tokenStore: sdkgen.TokenStoreInterface, scopes: List[str]):
        return Client("https://api.typehub.cloud/", sdkgen.OAuth2(clientId, clientSecret, "https://api.typehub.cloud/authorization/token", "", tokenStore, scopes))

