"""
common_form_element_checkbox automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .common_form_element import CommonFormElement


# Form element which represents a checkbox element
class CommonFormElementCheckbox(CommonFormElement):
    type: Literal["checkbox"] = Field(alias="type")
    pass


