"""
CommonMessageException automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import sdkgen

from .common_message import CommonMessage

class CommonMessageException(sdkgen.KnownStatusCodeException):
    payload: CommonMessage = None

    @classmethod
    def __init__(cls, payload):
        cls.payload = CommonMessage.model_validate_json(json_data=payload)

    @classmethod
    def get_payload(cls) -> CommonMessage:
        return cls.payload
