"""
common_agent_input automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .common_agent_content import CommonAgentContent
from .common_agent_content_binary import CommonAgentContentBinary
from .common_agent_content_choice import CommonAgentContentChoice
from .common_agent_content_object import CommonAgentContentObject
from .common_agent_content_text import CommonAgentContentText
from .common_agent_content_tool_call import CommonAgentContentToolCall


# This object represents an agent input
class CommonAgentInput(BaseModel):
    previous_id: Optional[str] = Field(default=None, alias="previousId")
    input: Annotated[Union["CommonAgentContentBinary", "CommonAgentContentChoice", "CommonAgentContentObject", "CommonAgentContentText", "CommonAgentContentToolCall"], Field(discriminator="type")] = Field(alias="input")
    pass


