"""
common_form_container automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .common_form_element import CommonFormElement


class CommonFormContainer(BaseModel):
    element: Optional[List[CommonFormElement]] = Field(default=None, alias="element")
    pass


