"""
common_form_element_text_area automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .common_form_element import CommonFormElement


# Form element which represents a textarea
class CommonFormElementTextArea(CommonFormElement):
    type: Literal["http://fusio-project.org/ns/2015/form/textarea"] = Field(alias="type")
    mode: Optional[str] = Field(default=None, alias="mode")
    pass


