"""
consumer_webhook_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class ConsumerWebhookResponse:
    status: int
    code: int
    attempts: str
    execute_date: str
