"""
consumer_user_activate automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class ConsumerUserActivate:
    token: str = field(default=None, metadata=config(field_name="token"))
