"""
consumer_user_plan automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class ConsumerUserPlan:
    id: int = field(default=None, metadata=config(field_name="id"))
    name: str = field(default=None, metadata=config(field_name="name"))
    price: int = field(default=None, metadata=config(field_name="price"))
    points: int = field(default=None, metadata=config(field_name="points"))
    period: int = field(default=None, metadata=config(field_name="period"))
