"""
consumer_form automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .common_metadata import CommonMetadata


# Dynamic form configuration entity
class ConsumerForm(BaseModel):
    kind: Optional[str] = Field(default=None, alias="kind")
    id: Optional[int] = Field(default=None, alias="id")
    name: Optional[str] = Field(default=None, alias="name")
    action: Optional[str] = Field(default=None, alias="action")
    method: Optional[str] = Field(default=None, alias="method")
    json_schema: Optional[Any] = Field(default=None, alias="jsonSchema")
    ui_schema: Optional[Any] = Field(default=None, alias="uiSchema")
    metadata: Optional[CommonMetadata] = Field(default=None, alias="metadata")


