"""
consumer_webhook_create automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class ConsumerWebhookCreate:
    event: str = field(default=None, metadata=config(field_name="event"))
    name: str = field(default=None, metadata=config(field_name="name"))
    endpoint: str = field(default=None, metadata=config(field_name="endpoint"))
