"""
consumer_token_create automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from typing import List
@dataclass_json
@dataclass
class ConsumerTokenCreate:
    name: str = field(metadata=config(field_name="name"))
    scopes: List[str] = field(metadata=config(field_name="scopes"))
    expire: datetime.date = field(metadata=config(field_name="expire"))
