"""
consumer_user_login automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from typing import List
@dataclass_json
@dataclass
class ConsumerUserLogin:
    username: str = field(default=None, metadata=config(field_name="username"))
    password: str = field(default=None, metadata=config(field_name="password"))
    scopes: List[str] = field(default=None, metadata=config(field_name="scopes"))
