"""
consumer_identity automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
@dataclass_json
@dataclass
class ConsumerIdentity:
    id: int = field(default=None, metadata=config(field_name="id"))
    name: str = field(default=None, metadata=config(field_name="name"))
    icon: str = field(default=None, metadata=config(field_name="icon"))
    redirect: str = field(default=None, metadata=config(field_name="redirect"))
