"""
marketplace_bundle_schema automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .marketplace_bundle_schema_source import MarketplaceBundleSchemaSource


class MarketplaceBundleSchema(BaseModel):
    name: Optional[str] = Field(default=None, alias="name")
    source: Optional[MarketplaceBundleSchemaSource] = Field(default=None, alias="source")
    pass


