"""
marketplace_bundle_action automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .marketplace_bundle_action_config import MarketplaceBundleActionConfig


class MarketplaceBundleAction(BaseModel):
    name: Optional[str] = Field(default=None, alias="name")
    class_: Optional[str] = Field(default=None, alias="class")
    config: Optional[MarketplaceBundleActionConfig] = Field(default=None, alias="config")
    pass


