"""
system_api_catalog automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .system_api_catalog_link_set import SystemAPICatalogLinkSet


class SystemAPICatalog(BaseModel):
    linkset: Optional[List[SystemAPICatalogLinkSet]] = Field(default=None, alias="linkset")
    pass


