"""
system_about automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config
from typing import List
from system_about_apps import SystemAboutApps
from system_about_link import SystemAboutLink
@dataclass_json
@dataclass
class SystemAbout:
    api_version: str = field(metadata=config(field_name="apiVersion"))
    title: str = field(metadata=config(field_name="title"))
    description: str = field(metadata=config(field_name="description"))
    terms_of_service: str = field(metadata=config(field_name="termsOfService"))
    contact_name: str = field(metadata=config(field_name="contactName"))
    contact_url: str = field(metadata=config(field_name="contactUrl"))
    contact_email: str = field(metadata=config(field_name="contactEmail"))
    license_name: str = field(metadata=config(field_name="licenseName"))
    license_url: str = field(metadata=config(field_name="licenseUrl"))
    payment_currency: str = field(metadata=config(field_name="paymentCurrency"))
    categories: List[str] = field(metadata=config(field_name="categories"))
    scopes: List[str] = field(metadata=config(field_name="scopes"))
    apps: SystemAboutApps = field(metadata=config(field_name="apps"))
    links: List[SystemAboutLink] = field(metadata=config(field_name="links"))
