"""
SystemPaymentTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen

from common_message import CommonMessage
from common_message_exception import CommonMessageException

class SystemPaymentTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)
    pass


    def webhook(self, provider: str) -> CommonMessage:
        try:
            pathParams = {}
            pathParams["provider"] = provider

            queryParams = {}

            queryStructNames = [];

            url = self.parser.url("/system/payment/:provider/webhook", pathParams)

            headers = {}

            response = self.http_client.post(url, headers=headers, params=this.parser.query(queryParams, queryStructNames))

            if response.status_code >= 200 and response.status_code < 300:
                return CommonMessage.from_json(response.content)

            if response.status_code == 500:
                raise CommonMessageException(CommonMessage.from_json(response.content))

            raise sdkgen.UnknownStatusCodeException("The server returned an unknown status code")
        except Exception as e:
            raise sdkgen.ClientException("An unknown error occurred: " + str(e))
    pass


