"""
SystemTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .system_connection_tag import SystemConnectionTag
from .system_meta_tag import SystemMetaTag
from .system_payment_tag import SystemPaymentTag

class SystemTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)

    def connection(self) -> SystemConnectionTag:
        return SystemConnectionTag(
            self.http_client,
            self.parser
        )

    def meta(self) -> SystemMetaTag:
        return SystemMetaTag(
            self.http_client,
            self.parser
        )

    def payment(self) -> SystemPaymentTag:
        return SystemPaymentTag(
            self.http_client,
            self.parser
        )


