"""
system_captcha_challenge automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal


class SystemCaptchaChallenge(BaseModel):
    algorithm: Optional[str] = Field(default=None, alias="algorithm")
    challenge: Optional[str] = Field(default=None, alias="challenge")
    maxnumber: Optional[int] = Field(default=None, alias="maxnumber")
    salt: Optional[str] = Field(default=None, alias="salt")
    signature: Optional[str] = Field(default=None, alias="signature")
    expires: Optional[int] = Field(default=None, alias="expires")


