"""
backend_connection_index_entry automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class BackendConnectionIndexEntry:
    name: str
    _class: str
