"""
backend_app_token_collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from common_collection import CommonCollection
from backend_app_token import BackendAppToken
@dataclass_json
@dataclass
class BackendAppTokenCollection(CommonCollection[BackendAppToken]):
    pass
