"""
consumer_user_account automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
from consumer_user_plan import ConsumerUserPlan
from common_metadata import CommonMetadata
@dataclass_json
@dataclass
class ConsumerUserAccount:
    id: int
    plan_id: int
    status: int
    name: str
    email: str
    points: int
    scopes: List[str]
    plans: List[ConsumerUserPlan]
    metadata: CommonMetadata
    date: datetime.datetime
