"""
consumer_user_jwt automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class ConsumerUserJWT:
    token: str
    expires_in: int
    refresh_token: str
    scope: str
